### ISSUE TITLE
Carousel: duplicate keys

### ISSUE THREAD

**Issue by MorganeLecurieux** [canalplus/react-keys#69]
When there's just a few items in the carousel, it duplicates some of the items to make it work.
As the __element id__ is taken for the __key__, the key is the same for the duplicated elements. This crashes an error.

We just need to make the key according to the index and it will work : 

_In Carousel.jsx_
```js
      {elements.map((element, inc) => {
        // code
        return <div key={`${element.props.id}-${inc}`} /*...*/ >{element}</div>;
      })}
```

**Comment by FlorentD** [comment]
Should be allright now !
